language: python
sudo: false
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install python-coveralls
  - pip install -q -r requirements.txt
  - pip install --editable .
script:
  - flake8 .
  - pytest -v --tb=native --cov
after_success:
  - coveralls
deploy:
  provider: pypi
  user: theskumar
  password:
    secure: DXUkl4YSC2RCltChik1csvQulnVMQQpD/4i4u+6pEyUfBMYP65zFYSNwLh+jt+URyX+MpN/Er20+TZ/F/fu7xkru6/KBqKLugeXihNbwGhbHUIkjZT/0dNSo03uAz6s5fWgqr8EJk9Ll71GexAsBPx2yqsjc2BMgOjwcNly40Co=
  on:
    tags: true
    repo: theskumar/python-dotenv
