language: python
sudo: false
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy
install:
  - pip install python-coveralls docutils
  - pip install -q -r requirements.txt
  - pip install --editable .
script:
  - flake8 .
  - pytest -v --tb=native --cov
  - |
    if python -c 'import sys; sys.exit(0 if sys.version_info >= (3, 4) else 1)' ; then
      python setup.py check --metadata --restructuredtext --strict
    fi
after_success:
  - coveralls
deploy:
  provider: pypi
  user: theskumar
  password:
    secure: VdULnucEUBZB0qZFKrP0kGdxYOY02QrvJBvVAHDc4CBhvPWcfF5HpEWD1CDNr2wdvg5Wwi5WGgX66Rthkrsw6akPwB+aPA++bFZ0uMHy392Nu4hxusX915R3JGnQ7L53aYrohOsJ7JsrZ7n12I38LJSewfkyQydAxjhJA+3hAtw=
  on:
    tags: true
    repo: theskumar/python-dotenv
