language: python
python:
  - '2.7'
  - '3.3'
  - pypy
install:
  - pip install -q -r requirements.txt
  - pip install --editable .
before_script: flake8
script: py.test
deploy:
  provider: pypi
  user: 'theskumar'
  password:
    secure: xe5yaUqAb0jam6epvEGSUMYt9L5gSRyFLaahTmCDEULP7msj8D45vswV/uEvnjdWdBw5CPuBkhLJXj2vsVMjkWVSa6bBfz79sEdd//70lE07bJA9sBSsXwbB4hxY+jWgW1KTFUNCPFP59L0ZosgYHJMbLcyr8iH2ZI+QzyUrO1U=
