language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- pypy
install:
- pip install python-coveralls
- pip install -q -r requirements.txt
- pip install --editable .
before_script: flake8
script:
- coverage run --source=dotenv.py --omit='*tests*' -m py.test tests/ -v --tb=native
- coverage report
after_script:
- coveralls
deploy:
  provider: pypi
  user: theskumar
  password:
    secure: VdULnucEUBZB0qZFKrP0kGdxYOY02QrvJBvVAHDc4CBhvPWcfF5HpEWD1CDNr2wdvg5Wwi5WGgX66Rthkrsw6akPwB+aPA++bFZ0uMHy392Nu4hxusX915R3JGnQ7L53aYrohOsJ7JsrZ7n12I38LJSewfkyQydAxjhJA+3hAtw=
  on:
    tags: true
    repo: theskumar/python-dotenv
